language: node_js
node_js:
  - "node"
  - "lts/*"
jobs:
  include:
    - stage: test
      script: yarn run build && yarn run prepush
    - stage: storybook
      script: yarn run build-storybook
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./out
        verbose: true
        edge: true
        on:
          branch: master
    - stage: deploy
      deploy:
        cleanup: false
        edge: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
